### ISSUE TITLE
Extend database configuration with support for schema

### ISSUE THREAD

**Issue by hsn10** [mcorbin/meuse#22]
Add schema to database configuration. It will look like this.
```
database:
  user: "meuse"
  host: "127.0.0.1"
  name: "meuse"
  schema: "project1"
```
Tables will be created in that schema. It means that instead of tabname it would be project1.tabname.

This is a very easy to do. You just need to issue 2 SQL commands:

```
CREATE schema IF NOT EXISTS project1;
SET search_path TO project1;
```
and access tables like you normally do now.
