### ISSUE TITLE
Crates rename doesn't work with features (`package = ...`)

### ISSUE THREAD

**Issue by mexus** [mcorbin/meuse#36]
Hi and thanks for the great custom registry! :)

I've come over an issue that i don't know how to handle: it's impossible to use a crate that renames a crate and uses it as a feature.

Step to reproduce:
1. Create two crates: `$ cargo init --lib test-crate` and `$ cargo init --lib use-test-crate`.
2. Set up the `test-crate` (`test-crate/Cargo.toml`):
```toml
[package]
name = "test-crate"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
with = [ "bit-vec6" ]

[dependencies]
bit-vec6 = { version = "0.6", package = "bit-vec" }
```
3. Set up the `use-test-crate` (`use-test-crate/Cargo.toml`):
```toml
[package]
name = "use-test-crate"
version = "0.1.0"
authors = []
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
test-crate = { version = "0.1.0", registry = "REGISTRY-NAME"}
```
4. Publish the `test-crate`: `$ cd test-crate && cargo publish --registry REGISTRY-NAME`
5. Try to build the `use-test-crate`: `$ cd use-test-crate && cargo check`

```
    Updating `ssh://git@..../crates-index.git` index
error: no matching package named `test-crate` found
location searched: registry `ssh://git@.../crates-index.git`
required by package `use-test-crate v0.1.0 (/home/mexus/test/rust/use-test-crate)`
```

`cargo search` however returns the expected results though:

```
$ cargo search --registry REGISTRY-NAME test-crate
test-crate = "0.1.0"    #
```

Any ideas how to fix the issue? :)
